#!/bin/bash
#
# Generic script for collecting data on a set of submissions
# Acknowledgement - Rachel Cardell-Oliver for initial script that has been adapted

# Alex Bagini, August 2011

#Location of student submissions
SUBDIR=/home/alex/student-code/Java1200-BankAccount-2011-1/submissions
#Location of bash scripts
SCRIPTDIR=/home/alex/Dropbox/Uni-2011/Honours/dev/scripts/bank-account
#Location of output directory
OUTDIR=/home/alex/output-bank-account

MATRIX=/home/alex/Bank-Account-Matrix.txt

#Matrix file preamble
if [ -f $MATRIX ] ; then
	rm $MATRIX
fi

echo -e "           \t |Deposit\t         \t          \t           \t\t\t|Withdraw" >> $MATRIX
echo -e "StuID \t\t |Pass \t GM_If \t GM_Else \t GM_Exprs \t GM_GuardVar \t|Pass \t GM_If \t GM_Else \t GM_Exprs \t GM_GuardVar" >> $MATRIX
echo 	"----------------------------------------------------------------------------------------------------------------------" >> $MATRIX

#Run checks for all students
if [ -d $OUTDIR ] ; then
	echo "Removing previous output directory"
	rm -r $OUTDIR
	mkdir -m 777 $OUTDIR
fi

cd $SUBDIR
for i in *
do
  # for each student submissions perform checkstyle
  if [ -d $i ]; then
	echo "Marking $i"
	bash $SCRIPTDIR/checkstyle-script-bank $i
  fi
done

#Execute summary script
bash $SCRIPTDIR/checkstyle-analyse-bank

exit 0
