#!/bin/bash
# Script to run checkstyle using custom checks on SUBDIR student submissions
# Acknowledgement - Rachel Cardell-Oliver for providing initial script that has been adapted

# Alex Bagini May, 2011

# Student folder
STU=$1    ; shift


# Variables
TESTDIR=/home/alex/Dropbox/Uni-2011/Honours/dev/src-test
SUBDIR=/home/alex/student-code/Java1200-BankAccount-2011-1
OUTDIR=/home/alex/output-bank-account

PROG=BankAccount

CHECKRULES=$TESTDIR/guardcheck
CHECKSTYLE=$TESTDIR/checkstyle-5.3-all.jar
CUSTOMRULES=$TESTDIR/update.jar

#check student dir exists
STUDIR=$SUBDIR/submissions/$STU
if [ ! -d $STUDIR ] ; then
    echo "Directory $STUDIR not found"
    exit 1
fi

#check output dir exists
if [ ! -d $OUTDIR ] ; then
	echo "Creating $OUTDIR"
	mkdir -m 777 $OUTDIR
fi

#check student output dir exists
if [ ! -d $OUTDIR/$STU ] ; then
	echo "Created dir $OUTDIR/$STU"
	mkdir -m 777 $OUTDIR/$STU
fi

FEEDBACK=$OUTDIR/$STU/Feedback.txt
SUMMARY=$OUTDIR/Summary.txt

echo "Marking $PROG for $STU at $(date +%Y-%m-%d" "%H:%M)" > $FEEDBACK #start a new feedback file

cd $STUDIR

#1. check file exists
if [ ! -f $PROG.java ] ; then
   echo "$PROG.java not found. Please check file name and resubmit"
   exit 1
else
	echo "$PROG.java found"
	echo "$PROG.java file submitted." >> $FEEDBACK
fi


#2. Run checkstyle tests with custom java pattern checks
function runcheckstyletests() {
    RULESET=$1
	echo "Running Checkstyle with $RULESET.xml configuration." >> $FEEDBACK
	CS=`java -classpath $CUSTOMRULES:$CHECKSTYLE com.puppycrawl.tools.checkstyle.Main -c $CHECKRULES.xml $PROG.java  | wc -l`
	
	#Output results regardless to summary file to be analysed later
	java -classpath $CUSTOMRULES:$CHECKSTYLE com.puppycrawl.tools.checkstyle.Main -c $CHECKRULES.xml $PROG.java >> $SUMMARY	

	# Marks allocation based on errors encountered
	# TODO Need to adjust this as CS outputs Success messages in audit now as well.
	if [ $CS -gt 2 ]; then
		CS=$[$CS-2] #subtracting 2 for audit lines, leaves number of checkstyle warnings
		#BM=0
		echo "$CS checkstyle pattern violation(s) reported:" >> $FEEDBACK
		java -classpath $CUSTOMRULES:$CHECKSTYLE com.puppycrawl.tools.checkstyle.Main -c $CHECKRULES.xml $PROG.java >> $FEEDBACK
	else
	    CS=0
		echo "Well done there are no checkstyle pattern violations reported." >> $FEEDBACK
	fi
}

runcheckstyletests $CHECKRULES

exit 0

