#!/bin/bash
#
# Generic script for collecting data on a set of submissions
# Acknowledgement - Rachel Cardell-Oliver for initial script that has been adapted

# Alex Bagini, May 2011

# Update to include Std Dev Feb 2012.

#Location of student submissions
SUBDIR=~/WeatherRecordArchive/submissions
#Location of bash scripts
SCRIPTDIR=~/JavaPatterns/dev/scripts/weather
#Location of output folder
OUTDIR=/home/baggers/output-weather

MATRIX=/home/baggers/Weather-Matrix-MaxMin.txt
MATRIX2=/home/baggers/Weather-Matrix-SDAvg.txt

#Matrix file preamble
if [ -f $MATRIX ] ; then
	rm $MATRIX
fi

echo -e "           \t |Maximum\t         \t          \t\t\t\t\t\t|Minimum" >> $MATRIX
echo -e "StuID \t\t |Pass \t SFL_For \t SFL_ForCond \t SFL_LocalVarRead \t SFL_LocalVarWrite \t|Pass \t SFL_For \t SFL_ForCond \t SFL_LocalVarRead \t SFL_LocalVarWrite" >> $MATRIX
echo 	"----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------" >> $MATRIX


#Matrix file preamble
if [ -f $MATRIX2 ] ; then
	rm $MATRIX2
fi

echo -e "           \t |Std Dev \t	\t	\t\t\t\t\t\t|Average" >> $MATRIX2
echo -e "StuID \t\t |Pass \t SFL_For \t SFL_ForCond \t SFL_LocalVarRead \t SFL_LocalVarWrite \t|Pass \t SFL_For \t SFL_ForCond \t SFL_LocalVarRead \t SFL_LocalVarWrite " >> $MATRIX2
echo 	"----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------" >> $MATRIX2

if [ -d $OUTDIR ] ; then
	echo "Removing previous output directory"
	rm -r $OUTDIR
	mkdir -m 777 $OUTDIR
fi

cd $SUBDIR
for i in *
do
  # for each name in the student submissions run checkstyle
  if [ -d $i ]; then
	echo "Marking $i"
	bash $SCRIPTDIR/checkstyle-script-weather $i
  fi
done

#Execute summary script
bash $SCRIPTDIR/checkstyle-analyse-weather

exit 0
